### ISSUE TITLE
Can you send me the sample image?

### ISSUE THREAD

**Issue by xuyifeng-nwpu** [IDKiro/Auto-to-See-in-the-Dark#1]
Thank you share your code.
The sample image  of the "simple.py" can not be downloaded. Can you send me the sample image?

My email is 42805959@qq.com.

Thank.

**Comment by IDKiro** [comment]
It may be blocked by GFW since it needs to be downloaded from google drive.

**Comment by IDKiro** [comment]
> Thank you share your code.
> The sample image of the "simple.py" can not be downloaded. Can you send me the sample image?
> 
> My email is [42805959@qq.com](mailto:42805959@qq.com).
> 
> Thank.

我可以发你一张，你不能跑很可能是因为你没翻墙没法从google drive下模型和图片。
这是我很早时候的随手写的代码，具体只能靠你自行阅读代码了。

**Comment by xuyifeng-nwpu** [comment]
你的中文真地道，中国人？ 
之前通过tiff确实能恢复吗？

**Comment by IDKiro** [comment]
> 你的中文真地道，中国人？
> 之前通过tiff确实能恢复吗？

我是中国人，我现在把示例图片发给你，你放在 result/simple_test 文件夹下面就可以跑 simple.py 了，我刚跑了下是没问题的，test.py 那个我就没法测了，因为我生成的数据集早就删了。

**Comment by xuyifeng-nwpu** [comment]
网站上可以下载的模型仅仅适用于这一张demo示例图片？
如果需要跑sony数据库里面的图片转换过来的tiff图片，需要重新训练，使用新的训练模型？

麻烦你发我qq邮箱吧，谢谢。有机会多请教，多沟通。

**Comment by IDKiro** [comment]
> 网站上可以下载的模型仅仅适用于这一张demo示例图片？
> 如果需要跑sony数据库里面的图片转换过来的tiff图片，需要重新训练，使用新的训练模型？
> 
> 麻烦你发我qq邮箱吧，谢谢。有机会多请教，多沟通。

刚才就发了。模型是一样的，可能是 test.py 代码错了。当时可能因为图片太大了，会炸显存只能用CPU跑，所以 test.py 没经过测试。
具体只能靠你自己研究了，这个 issue 我关掉了。
