### ISSUE TITLE
The output result is still black.

### ISSUE THREAD

**Issue by xuyifeng-nwpu** [IDKiro/Auto-to-See-in-the-Dark#2]
I try the code, but the output result image is still black.

The test process is as below:
1:I select randomly a picture from the "short" fold in the trainset and rename the image name to "10111_00_0.1s.tiff". ( The tiff files have been converted by "raw2tiff.py")
2:Then a picture named "10111_00_30s.tiff" is putted to the "long" fold.
3:python test.py

Thanks.

**Comment by IDKiro** [comment]
Have you downloaded the model?

**Comment by xuyifeng-nwpu** [comment]
Yes, I have dowloaded the model.
The model has two files: model.ckpt.data-00000-of-00001( 90934kB)  and model.ckpt.meta (435kB).

I copied the two files to the fold "checkpoint".
