### ISSUE TITLE
I still have not received the sample picture。邮箱仍然没有收到示例图片。

### ISSUE THREAD

**Issue by xuyifeng-nwpu** [IDKiro/Auto-to-See-in-the-Dark#3]
兄弟，我又去看了我的42805959@qq.com邮箱，还是没有收到。
我还有一个邮箱：xuyifeng123@mail.nwpu.edu.cn。

真的不行的话，您可以直接发我qq吗？

会不会您是国外的邮箱，最近中美贸易战有影响啊。

**Comment by IDKiro** [comment]
重新发送了
